on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run migrations , clear cache for views, config and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd public_html/tagir-astgdam.const-tech.in
            git pull https://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@github.com/const-tech/tagir-astgdam.git
            php artisan migrate
            php artisan optimize:clear            
          host: 84.16.241.139
          user: consttechin
          port: 2204
          key: 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
          pass: "Y4b7B-70C?*}"
          args: -tt
